# This file was generated by GoReleaser. DO NOT EDIT.
cask "norka-cli" do
  version "1.6.0"

  on_macos do
    on_arm do
      sha256 "546e1ebb773cdb3b890e5c045bfa40f799e6c5b53267370f75df7b1400f96a1b"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "43cb209c00c259744a71603e826a55d3b5be8d73d636280fd5f1901ff4514ddb"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "95a0be4b0b13c02c42b5d427987f76e3e1089600d3822950487ce7c52aeba240"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "534738a71c34ffba7985fb3bde77add96ef6fe89e1517ec8b94b73a748a7f943"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "norka-cli"
  desc "Command-line client and background daemon for the Norka tunnel app."
  homepage "https://github.com/norka-app/Norka"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "norka-cli"
  binary "norkad"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/norka-cli"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/norkad"]
    end
  end

  # No zap stanza required
end
