# This file was generated by GoReleaser. DO NOT EDIT.
cask "norka-cli" do
  version "1.5.0"

  on_macos do
    on_arm do
      sha256 "277cc7ba45aa56c6a48df515d9e4d3e4e9d3a12175daee902831dc5d6b3c3d1a"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eadb6ca34e4a05e25a50c6a66a7201de927344ea341609d1c48d710a5998bf3b"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "eebed2fb4b8cbbaf9712908b2a031870b0d66a6960ea5a058068f06c2c78d59a"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "047ea3b4588dcba1ff31b425ac02340d60af5e9109a6b906d99a9ca21c58db44"
      url "https://github.com/norka-app/Norka/releases/download/v#{version}/norka-cli_#{version}_linux_amd64.tar.gz"
    end
  end

  name "norka-cli"
  desc "Command-line client for the Norka tunnel app."
  homepage "https://github.com/norka-app/Norka"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "norka-cli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/norka-cli"]
    end
  end

  # No zap stanza required
end
